namespace BikeRental.Contracts.Dtos;

/// <summary>
/// Data transfer object representing total profit generated by a specific bike model.
/// </summary>
public class TopModelProfitDto
{
    /// <summary>
    /// Name of the bike model.
    /// </summary>
    public string Model { get; set; } = string.Empty;

    /// <summary>
    /// Total profit generated by the model.
    /// </summary>
    public decimal Profit { get; set; }
}
